create table if not exists public.users (
  id bigint generated by default as identity primary key,
  nickname text not null,
  email text not null unique,
  password_hash text not null,
  balance integer not null default 0,
  avatar text not null default 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=200&h=200&auto=format&fit=crop',
  bio text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  trainer_id integer not null,
  trainer_name text not null,
  game text not null,
  character_name text not null,
  duration_minutes integer not null,
  level integer not null check (level between 1 and 10),
  time_slot text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_bookings_user_id on public.bookings(user_id);

